namespace ClearPilot.Core.Localization;

public sealed class MessageCatalog
{
    private readonly IReadOnlyDictionary<StringKey, string> messages;

    private MessageCatalog(Language language, IReadOnlyDictionary<StringKey, string> messages)
    {
        Language = language;
        this.messages = messages;
    }

    public Language Language { get; }

    public static MessageCatalog For(Language language)
    {
        return language switch
        {
            Language.SimplifiedChinese => new MessageCatalog(language, SimplifiedChineseMessages),
            _ => new MessageCatalog(Language.English, EnglishMessages)
        };
    }

    public string Get(StringKey key)
    {
        return messages.TryGetValue(key, out var value)
            ? value
            : EnglishMessages[key];
    }

    private static readonly IReadOnlyDictionary<StringKey, string> EnglishMessages = new Dictionary<StringKey, string>
    {
        [StringKey.AppTitle] = "ClearPilot",
        [StringKey.MainMenuQuickSafeClean] = "Quick Safe Clean",
        [StringKey.MainMenuScanRecommendedItems] = "Scan Recommended Items",
        [StringKey.MainMenuDeepSpaceAnalysis] = "Deep Space Analysis",
        [StringKey.MainMenuCleanupHistory] = "Cleanup History",
        [StringKey.MainMenuSettings] = "Settings",
        [StringKey.MainMenuQuickSafeCleanDescription] = "safe automatic cleanup",
        [StringKey.MainMenuScanRecommendedItemsDescription] = "confirmed cache cleanup",
        [StringKey.MainMenuDeepSpaceAnalysisDescription] = "review large files",
        [StringKey.MainMenuCleanupHistoryDescription] = "logs and retention",
        [StringKey.MainMenuSettingsDescription] = "language and behavior",
        [StringKey.MainMenuExitDescription] = "close ClearPilot",
        [StringKey.MenuExit] = "Exit",
        [StringKey.PromptChooseOption] = "Choose an option: ",
        [StringKey.MessageInvalidOption] = "Invalid option. Please try again.",
        [StringKey.MessagePressEnterToContinue] = "Press Enter to continue...",
        [StringKey.MenuCancel] = "Cancel",
        [StringKey.CleanupPreviewTitle] = "Cleanup preview",
        [StringKey.CleanupPreviewRules] = "Cleanup groups",
        [StringKey.CleanupPreviewFiles] = "Estimated files",
        [StringKey.CleanupPreviewSpace] = "Estimated space",
        [StringKey.CleanupPreviewTopItems] = "Top items",
        [StringKey.CleanupPreviewSafety] = "Safety boundary",
        [StringKey.QuickSafeCleanPreviewSafety] = "Safety boundary: S0-only known very-low-risk temporary/cache cleanup targets.",
        [StringKey.QuickSafeCleanStarted] = "Running Quick Safe Clean...",
        [StringKey.QuickSafeCleanNoItems] = "No S0 cleanup items were found.",
        [StringKey.QuickSafeCleanCompleted] = "Quick Safe Clean completed.",
        [StringKey.QuickSafeCleanDeletedFiles] = "Deleted files",
        [StringKey.QuickSafeCleanReclaimedSpace] = "Reclaimed space",
        [StringKey.QuickSafeCleanDryRunFiles] = "Dry-run files",
        [StringKey.QuickSafeCleanDryRunSpace] = "Dry-run space",
        [StringKey.QuickSafeCleanSkippedItems] = "Skipped items",
        [StringKey.QuickSafeCleanFailedItems] = "Failed items",
        [StringKey.QuickSafeCleanLogPath] = "Log folder",
        [StringKey.QuickSafeCleanLogError] = "Log write error",
        [StringKey.QuickSafeCleanBoundaryS0Only] = "Safety boundary: S0-only.",
        [StringKey.QuickSafeCleanBoundaryKnownTargetsOnly] = "ClearPilot will clean only known very-low-risk temporary/cache targets in this mode.",
        [StringKey.QuickSafeCleanBoundaryBroaderElsewhere] = "Broader cleanup opportunities are not included in Quick Safe Clean.",
        [StringKey.QuickSafeCleanSkippedUnchangedNote] = "Skipped items were left unchanged.",
        [StringKey.QuickSafeCleanSkippedReasonSummary] = "Skipped reasons",
        [StringKey.QuickSafeCleanSkippedReasonLocked] = "Locked or in use",
        [StringKey.QuickSafeCleanSkippedReasonInaccessible] = "Inaccessible or access denied",
        [StringKey.QuickSafeCleanSkippedReasonOutsideBoundary] = "Outside S0 safety boundary or protected by safety policy",
        [StringKey.QuickSafeCleanSkippedReasonOther] = "Other reason",
        [StringKey.QuickSafeCleanFailureNoElevation] = "ClearPilot does not retry with elevated privileges, service stopping, ACL changes, or forced unlock.",
        [StringKey.RecommendedScanStarted] = "Scanning recommended cleanup items...",
        [StringKey.RecommendedScanNoItems] = "No S1 recommended cleanup items were found.",
        [StringKey.RecommendedScanFound] = "Recommended cleanup items found:",
        [StringKey.RecommendedScanCategory] = "Category",
        [StringKey.RecommendedScanRisk] = "Risk",
        [StringKey.RecommendedScanFiles] = "Files",
        [StringKey.RecommendedScanEstimatedSpace] = "Estimated space",
        [StringKey.RecommendedScanExplanation] = "Explanation",
        [StringKey.RecommendedActionHint] = "Action: select item numbers, then explicitly confirm. Default is No.",
        [StringKey.RecommendedPreviewSafety] = "These S1 items require explicit selection and explicit confirmation before cleanup.",
        [StringKey.DeepAnalysisActionHint] = "Action: enter the item number to open its location; ClearPilot will not delete it.",
        [StringKey.RecommendedSelectionPrompt] = "Enter item numbers to clean, A for all recommended items, or 0 to cancel: ",
        [StringKey.RecommendedSelectionAll] = "Select all recommended S1 items",
        [StringKey.RecommendedSelectionCancelled] = "Recommended cleanup cancelled. No files were changed.",
        [StringKey.RecommendedCleanStarted] = "Cleaning selected recommended items...",
        [StringKey.RecommendedCleanCompleted] = "Recommended cleanup completed.",
        [StringKey.RecommendedCleanedFiles] = "Cleaned files",
        [StringKey.RecommendedReclaimedSpace] = "Reclaimed space",
        [StringKey.DeepAnalysisStarted] = "Running Deep Space Analysis...",
        [StringKey.DeepAnalysisScanScope] = "Scan scope",
        [StringKey.DeepAnalysisNoItems] = "No large review items were found.",
        [StringKey.DeepAnalysisFound] = "Deep Space Analysis findings:",
        [StringKey.DeepAnalysisSummary] = "Scan summary",
        [StringKey.DeepAnalysisScannedRoots] = "Scanned roots",
        [StringKey.DeepAnalysisScannedDirectories] = "Scanned directories",
        [StringKey.DeepAnalysisScannedFiles] = "Scanned files",
        [StringKey.DeepAnalysisReviewItems] = "Review items",
        [StringKey.DeepAnalysisReviewFootprint] = "Review footprint",
        [StringKey.DeepAnalysisTypeTotals] = "Type totals",
        [StringKey.DeepAnalysisTopSources] = "Top sources",
        [StringKey.DeepAnalysisCurrentView] = "Current view",
        [StringKey.DeepAnalysisFilterCommand] = "Filter findings",
        [StringKey.DeepAnalysisSortCommand] = "Sort findings",
        [StringKey.DeepAnalysisReportCommand] = "Export report",
        [StringKey.DeepAnalysisFilterPrompt] = "Choose a filter, or 0 to keep the current view: ",
        [StringKey.DeepAnalysisSortPrompt] = "Choose a sort mode, or 0 to keep the current view: ",
        [StringKey.DeepAnalysisFilterAll] = "All finding types",
        [StringKey.DeepAnalysisSortBySize] = "Size, largest first",
        [StringKey.DeepAnalysisSortByLastModified] = "Last modified, newest first",
        [StringKey.DeepAnalysisNoFilteredItems] = "No findings match the current filter.",
        [StringKey.DeepAnalysisType] = "Type",
        [StringKey.DeepAnalysisRisk] = "Risk",
        [StringKey.DeepAnalysisSize] = "Size",
        [StringKey.DeepAnalysisLastModified] = "Last modified",
        [StringKey.DeepAnalysisExplanation] = "Explanation",
        [StringKey.DeepAnalysisSuggestedAction] = "Suggested action",
        [StringKey.DeepAnalysisTypeLargeFile] = "Large file",
        [StringKey.DeepAnalysisTypeLargeFolder] = "Large folder",
        [StringKey.DeepAnalysisTypeOldArchiveOrInstaller] = "Old archive or installer",
        [StringKey.DeepAnalysisTypeProjectDependencyFolder] = "Project dependency folder",
        [StringKey.DeepAnalysisTypeFileTypeSummary] = "File type summary",
        [StringKey.DeepAnalysisOpenPrompt] = "Enter an item number to open its location, F to filter, S to sort, R to export, or 0 to return: ",
        [StringKey.DeepAnalysisOpenSuccess] = "Opened location in File Explorer.",
        [StringKey.DeepAnalysisOpenFailed] = "Could not open location",
        [StringKey.DeepAnalysisReportExportSuccess] = "Report exported",
        [StringKey.DeepAnalysisReportExportFailed] = "Could not export report",
        [StringKey.DeepAnalysisReportOpenLocationFailed] = "Report was exported, but ClearPilot could not open its folder",
        [StringKey.DeepAnalysisReviewOnlyNotice] = "Analysis only: Deep Space does not delete files. Downloads is scanned for storage understanding only, and Desktop/Documents/Pictures/Videos/Music are not scanned by default.",
        [StringKey.DeepAnalysisReturn] = "Return",
        [StringKey.HistoryTitle] = "Cleanup History",
        [StringKey.HistoryNoLogs] = "No cleanup history was found.",
        [StringKey.HistoryRetentionDeleted] = "Old log files removed",
        [StringKey.HistoryStartedAt] = "Started at",
        [StringKey.HistoryMode] = "Mode",
        [StringKey.HistoryDeletedFiles] = "Deleted files",
        [StringKey.HistoryDeletedBytes] = "Deleted bytes",
        [StringKey.HistoryDryRunFiles] = "Dry-run files",
        [StringKey.HistorySkippedItems] = "Skipped items",
        [StringKey.HistoryFailedItems] = "Failed items",
        [StringKey.HistoryLogPath] = "Log path",
        [StringKey.PlaceholderQuickSafeClean] = "Quick Safe Clean will be implemented in Phase 3. No files were changed.",
        [StringKey.PlaceholderScanRecommendedItems] = "Recommended cleanup scanning will be implemented in Phase 4. No files were changed.",
        [StringKey.PlaceholderDeepSpaceAnalysis] = "Deep Space Analysis will be implemented in Phase 5. This mode will not delete files.",
        [StringKey.PlaceholderCleanupHistory] = "Cleanup History will be implemented in Phase 6.",
        [StringKey.SettingsTitle] = "Settings",
        [StringKey.SettingsLanguage] = "UI language",
        [StringKey.SettingsLogRetentionDays] = "Log retention days",
        [StringKey.SettingsAutoEmptyRecycleBin] = "Auto-empty Recycle Bin after cleanup",
        [StringKey.SettingsBack] = "Back",
        [StringKey.SettingsCurrentValue] = "Current value",
        [StringKey.SettingsLanguageTitle] = "Select UI language",
        [StringKey.SettingsLanguageEnglish] = "English",
        [StringKey.SettingsLanguageSimplifiedChinese] = "Simplified Chinese",
        [StringKey.SettingsLanguageUpdated] = "UI language updated.",
        [StringKey.SettingsRetentionPrompt] = "Enter log retention days (1-365): ",
        [StringKey.SettingsRetentionUpdated] = "Log retention setting updated.",
        [StringKey.SettingsRecycleBinWarning] = "Warning: Emptying the Recycle Bin may permanently delete files that were already there before ClearPilot ran. This action affects the entire Recycle Bin, not only files cleaned by ClearPilot.",
        [StringKey.SettingsRecycleBinEnable] = "Enable",
        [StringKey.SettingsRecycleBinDisable] = "Disable",
        [StringKey.SettingsValueEnabled] = "Enabled",
        [StringKey.SettingsValueDisabled] = "Disabled",
        [StringKey.SettingsRecycleBinUpdated] = "Recycle Bin setting updated."
    };

    private static readonly IReadOnlyDictionary<StringKey, string> SimplifiedChineseMessages = new Dictionary<StringKey, string>
    {
        [StringKey.AppTitle] = "ClearPilot",
        [StringKey.MainMenuQuickSafeClean] = "快速安全清理",
        [StringKey.MainMenuScanRecommendedItems] = "扫描推荐清理项",
        [StringKey.MainMenuDeepSpaceAnalysis] = "深度空间分析",
        [StringKey.MainMenuCleanupHistory] = "清理历史",
        [StringKey.MainMenuSettings] = "设置",
        [StringKey.MainMenuQuickSafeCleanDescription] = "自动清理极低风险缓存",
        [StringKey.MainMenuScanRecommendedItemsDescription] = "确认后清理推荐缓存",
        [StringKey.MainMenuDeepSpaceAnalysisDescription] = "只分析大文件和目录",
        [StringKey.MainMenuCleanupHistoryDescription] = "查看日志和保留策略",
        [StringKey.MainMenuSettingsDescription] = "语言和行为设置",
        [StringKey.MainMenuExitDescription] = "关闭 ClearPilot",
        [StringKey.MenuExit] = "退出",
        [StringKey.PromptChooseOption] = "请选择一个选项: ",
        [StringKey.MessageInvalidOption] = "无效选项，请重试。",
        [StringKey.MessagePressEnterToContinue] = "按 Enter 继续...",
        [StringKey.MenuCancel] = "取消",
        [StringKey.CleanupPreviewTitle] = "清理预览",
        [StringKey.CleanupPreviewRules] = "清理分组",
        [StringKey.CleanupPreviewFiles] = "预计文件",
        [StringKey.CleanupPreviewSpace] = "预计空间",
        [StringKey.CleanupPreviewTopItems] = "主要项目",
        [StringKey.CleanupPreviewSafety] = "安全边界",
        [StringKey.QuickSafeCleanPreviewSafety] = "安全边界：仅 S0 的已知极低风险临时文件/缓存目标。",
        [StringKey.QuickSafeCleanStarted] = "正在运行快速安全清理...",
        [StringKey.QuickSafeCleanNoItems] = "未找到可执行的 S0 清理项目。",
        [StringKey.QuickSafeCleanCompleted] = "快速安全清理已完成。",
        [StringKey.QuickSafeCleanDeletedFiles] = "已删除文件",
        [StringKey.QuickSafeCleanReclaimedSpace] = "释放空间",
        [StringKey.QuickSafeCleanDryRunFiles] = "试运行文件",
        [StringKey.QuickSafeCleanDryRunSpace] = "试运行空间",
        [StringKey.QuickSafeCleanSkippedItems] = "已跳过项目",
        [StringKey.QuickSafeCleanFailedItems] = "失败项目",
        [StringKey.QuickSafeCleanLogPath] = "日志目录",
        [StringKey.QuickSafeCleanLogError] = "日志写入错误",
        [StringKey.QuickSafeCleanBoundaryS0Only] = "安全边界：仅 S0。",
        [StringKey.QuickSafeCleanBoundaryKnownTargetsOnly] = "此模式下，ClearPilot 只会清理已知的极低风险临时文件/缓存目标。",
        [StringKey.QuickSafeCleanBoundaryBroaderElsewhere] = "更广泛的清理机会不会进入快速安全清理。",
        [StringKey.QuickSafeCleanSkippedUnchangedNote] = "已跳过项目保持不变。",
        [StringKey.QuickSafeCleanSkippedReasonSummary] = "跳过原因汇总",
        [StringKey.QuickSafeCleanSkippedReasonLocked] = "文件被占用或正在使用",
        [StringKey.QuickSafeCleanSkippedReasonInaccessible] = "不可访问或访问被拒绝",
        [StringKey.QuickSafeCleanSkippedReasonOutsideBoundary] = "超出 S0 安全边界或受安全策略保护",
        [StringKey.QuickSafeCleanSkippedReasonOther] = "其他原因",
        [StringKey.QuickSafeCleanFailureNoElevation] = "ClearPilot 不会使用提升权限重试，也不会停止服务、修改 ACL 或强制解锁。",
        [StringKey.RecommendedScanStarted] = "正在扫描推荐清理项目...",
        [StringKey.RecommendedScanNoItems] = "未找到 S1 推荐清理项目。",
        [StringKey.RecommendedScanFound] = "已找到推荐清理项目:",
        [StringKey.RecommendedScanCategory] = "分类",
        [StringKey.RecommendedScanRisk] = "风险",
        [StringKey.RecommendedScanFiles] = "文件数",
        [StringKey.RecommendedScanEstimatedSpace] = "预计空间",
        [StringKey.RecommendedScanExplanation] = "说明",
        [StringKey.RecommendedActionHint] = "操作：选择项目编号后，必须明确确认。默认不执行。",
        [StringKey.RecommendedPreviewSafety] = "这些 S1 项目需要你明确选择并明确确认后才会清理。",
        [StringKey.DeepAnalysisActionHint] = "操作：输入编号仅会打开位置；ClearPilot 不会删除。",
        [StringKey.RecommendedSelectionPrompt] = "输入要清理的编号，A 清理全部建议项，或输入 0 取消：",
        [StringKey.RecommendedSelectionAll] = "仅选择建议清理的 S1 项目",
        [StringKey.RecommendedSelectionCancelled] = "已取消推荐清理。未修改任何文件。",
        [StringKey.RecommendedCleanStarted] = "正在清理已选择的推荐项目...",
        [StringKey.RecommendedCleanCompleted] = "推荐清理已完成。",
        [StringKey.RecommendedCleanedFiles] = "已清理文件",
        [StringKey.RecommendedReclaimedSpace] = "释放空间",
        [StringKey.DeepAnalysisStarted] = "正在运行深度空间分析...",
        [StringKey.DeepAnalysisScanScope] = "扫描范围",
        [StringKey.DeepAnalysisNoItems] = "未找到需要复核的大型项目。",
        [StringKey.DeepAnalysisFound] = "深度空间分析结果:",
        [StringKey.DeepAnalysisSummary] = "扫描摘要",
        [StringKey.DeepAnalysisScannedRoots] = "扫描根目录",
        [StringKey.DeepAnalysisScannedDirectories] = "扫描目录",
        [StringKey.DeepAnalysisScannedFiles] = "扫描文件",
        [StringKey.DeepAnalysisReviewItems] = "复核项目",
        [StringKey.DeepAnalysisReviewFootprint] = "复核项占用",
        [StringKey.DeepAnalysisTypeTotals] = "类型合计",
        [StringKey.DeepAnalysisTopSources] = "最大来源",
        [StringKey.DeepAnalysisCurrentView] = "当前视图",
        [StringKey.DeepAnalysisFilterCommand] = "筛选结果",
        [StringKey.DeepAnalysisSortCommand] = "排序结果",
        [StringKey.DeepAnalysisReportCommand] = "导出报告",
        [StringKey.DeepAnalysisFilterPrompt] = "请选择筛选条件，或输入 0 保持当前视图: ",
        [StringKey.DeepAnalysisSortPrompt] = "请选择排序方式，或输入 0 保持当前视图: ",
        [StringKey.DeepAnalysisFilterAll] = "全部结果类型",
        [StringKey.DeepAnalysisSortBySize] = "按大小排序，最大优先",
        [StringKey.DeepAnalysisSortByLastModified] = "按最后修改时间排序，最新优先",
        [StringKey.DeepAnalysisNoFilteredItems] = "当前筛选条件下没有结果。",
        [StringKey.DeepAnalysisType] = "类型",
        [StringKey.DeepAnalysisRisk] = "风险",
        [StringKey.DeepAnalysisSize] = "大小",
        [StringKey.DeepAnalysisLastModified] = "最后修改",
        [StringKey.DeepAnalysisExplanation] = "说明",
        [StringKey.DeepAnalysisSuggestedAction] = "建议操作",
        [StringKey.DeepAnalysisTypeLargeFile] = "大文件",
        [StringKey.DeepAnalysisTypeLargeFolder] = "大目录",
        [StringKey.DeepAnalysisTypeOldArchiveOrInstaller] = "旧压缩包或安装包",
        [StringKey.DeepAnalysisTypeProjectDependencyFolder] = "项目依赖目录",
        [StringKey.DeepAnalysisTypeFileTypeSummary] = "文件类型统计",
        [StringKey.DeepAnalysisOpenPrompt] = "请输入编号以打开位置，F 筛选，S 排序，R 导出，或输入 0 返回: ",
        [StringKey.DeepAnalysisOpenSuccess] = "已在资源管理器中打开位置。",
        [StringKey.DeepAnalysisOpenFailed] = "无法打开位置",
        [StringKey.DeepAnalysisReportExportSuccess] = "报告已导出",
        [StringKey.DeepAnalysisReportExportFailed] = "无法导出报告",
        [StringKey.DeepAnalysisReportOpenLocationFailed] = "报告已导出，但 ClearPilot 无法打开报告所在目录",
        [StringKey.DeepAnalysisReviewOnlyNotice] = "仅分析：Deep Space 不删除文件。Downloads 仅用于存储占用了解；Desktop/Documents/Pictures/Videos/Music 默认不扫描。",
        [StringKey.DeepAnalysisReturn] = "返回",
        [StringKey.HistoryTitle] = "清理历史",
        [StringKey.HistoryNoLogs] = "未找到清理历史。",
        [StringKey.HistoryRetentionDeleted] = "已删除过期日志文件",
        [StringKey.HistoryStartedAt] = "开始时间",
        [StringKey.HistoryMode] = "模式",
        [StringKey.HistoryDeletedFiles] = "已删除文件",
        [StringKey.HistoryDeletedBytes] = "已删除大小",
        [StringKey.HistoryDryRunFiles] = "试运行文件",
        [StringKey.HistorySkippedItems] = "已跳过项目",
        [StringKey.HistoryFailedItems] = "失败项目",
        [StringKey.HistoryLogPath] = "日志路径",
        [StringKey.PlaceholderQuickSafeClean] = "快速安全清理将在后续阶段完善。当前未修改任何文件。",
        [StringKey.PlaceholderScanRecommendedItems] = "推荐清理扫描将在后续阶段完善。当前未修改任何文件。",
        [StringKey.PlaceholderDeepSpaceAnalysis] = "深度空间分析将在后续阶段完善。此模式不会删除文件。",
        [StringKey.PlaceholderCleanupHistory] = "清理历史将在后续阶段完善。",
        [StringKey.SettingsTitle] = "设置",
        [StringKey.SettingsLanguage] = "界面语言",
        [StringKey.SettingsLogRetentionDays] = "日志保留天数",
        [StringKey.SettingsAutoEmptyRecycleBin] = "清理后自动清空回收站",
        [StringKey.SettingsBack] = "返回",
        [StringKey.SettingsCurrentValue] = "当前值",
        [StringKey.SettingsLanguageTitle] = "选择界面语言",
        [StringKey.SettingsLanguageEnglish] = "English",
        [StringKey.SettingsLanguageSimplifiedChinese] = "简体中文",
        [StringKey.SettingsLanguageUpdated] = "界面语言已更新。",
        [StringKey.SettingsRetentionPrompt] = "请输入日志保留天数 (1-365): ",
        [StringKey.SettingsRetentionUpdated] = "日志保留设置已更新。",
        [StringKey.SettingsRecycleBinWarning] = "警告：清空回收站可能会永久删除 ClearPilot 运行前已存在于回收站中的文件。此操作会影响整个回收站，而不仅是 ClearPilot 清理的文件。",
        [StringKey.SettingsRecycleBinEnable] = "启用",
        [StringKey.SettingsRecycleBinDisable] = "禁用",
        [StringKey.SettingsValueEnabled] = "已启用",
        [StringKey.SettingsValueDisabled] = "已禁用",
        [StringKey.SettingsRecycleBinUpdated] = "回收站设置已更新。"
    };
}
